version: '3'

services:
  app:
    container_name: iad_backend
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - "./app:/app/app"
    env_file:
      - .env
      - prod.env

#    environment:
#      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
#    env_file:
#      - .env
#    depends_on:
#      - db